levels = {
    "world0": {
        'title': ['WWWWWWWWWWWWWWWWWWWW',
                  'W                  W',
                  'W         E        W',
                  'W        WW        W',
                  'W        vv        W',
                  'W      S vv S      W',
                  'W      WWbbWW      W',
                  'W      vv  vv      W',
                  'W    S vv  vv S    W',
                  'W    WWbbWWbbWW    W',
                  'W    vv  vv  vv    W',
                  'W  S vv SvvS vv S  W',
                  'W  WWbbWWbbWWbbWW  W',
                  'W Pvv  vv  vv  vv  W',
                  'WWWWWWWWWWWWWWWWWWWW'],
        "ending": ['WWWWWWWWWWWWWWWWWWWW',
                   'W                  W',
                   'W                  W',
                   'WWW  WW  WW  WW  WWW',
                   'W                  W',
                   'W  WW  WW  WW  WW  W',
                   'W                  W',
                   'W        P         W',
                   'WW                WW',
                   'W  WW  WW  WW  WW  W',
                   'W                  W',
                   'WWW  WW  WW  WW  WWW',
                   'W                  W',
                   'W                 EW',
                   'WWWWWWWWWWWWWWWWWWWW']
    },

    "world1": {
        "level0": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W P    c    c     EW',
                   'WWWW   WWWWWW   WWWW',
                   'Whhb            bhhW',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level1": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W P    c SS c     EW',
                   'WWWW   WWWWWW   WWWW',
                   'Whhb            bhhW',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level2": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W PS   c SS c   S EW',
                   'WWWW   WWWWWW   WWWW',
                   'Whhb            bhhW',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level3": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c SS c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'W PS   c WW c     EW',
                   'WWWW   WWWWWW  WWWWW',
                   'Whhb           WhhhW',
                   'W              W   W',
                   'WSSS   SS  SS WWSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level4": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c SS c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'WSPS   c WW c  SS EW',
                   'WWWW   WWWWWW  WWWWW',
                   'Whhb           WbhhW',
                   'W              W   W',
                   'WSSS   SS  SSSWWSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level5": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c SS c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'W      c WW c      W',
                   'WSPS   c vv c   S EW',
                   'WWWW   WWWWhW   WWWW',
                   'Whhb            bhhW',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level6": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c SS c      W',
                   'W      c WW c  WWWhW',
                   'W      c vv cWWW   W',
                   'W      c WW cv W   W',
                   'WSPS   c WW cv WSSEW',
                   'WWWW   WWWWWWbhWWWWW',
                   'Whhb               W',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level7": ['WWWWWWWWWWWWWWWWWWWW',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c      W',
                   'W      c    c  S   W',
                   'W      c ZWzc  WWhhW',
                   'W      c  v c  WW  W',
                   'W      c  v c  WW  W',
                   'WSPS   c  v c WWWSEW',
                   'WWWW   WWWWWW  WWWWW',
                   'Whhb           bhhhW',
                   'W                  W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level8": ['WWWWWWWWWWWWWWWWWWWW',
                   'W  v v c    c      W',
                   'W  v v c    c      W',
                   'W  v v c    c      W',
                   'WWWWWWWc    c      W',
                   'W   vZWc    c   S  W',
                   'W   vZWc ZWzc  ZWhhW',
                   'W   vZWc  v c  ZW  W',
                   'W   v Wc  v c  ZW  W',
                   'WSPSv  c  v cZWWWSEW',
                   'WWWWWWbWhWWWW  WWWWW',
                   'Whhb           bhhhW',
                   'W                  W',
                   'WSSSSS SWSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        "level9": ['WWWWWWWWWWWWWWWWWWWW',
                   'W  v v c vv  v v   W',
                   'W  v v c WWW v v   W',
                   'W  v v c  sWWWWWz  W',
                   'WWWWWWWc    c      W',
                   'W   vZWc    c   SS W',
                   'W   vZWc ZWzc  ZWWhW',
                   'W   vZWc  v c  ZWs W',
                   'W   v Wc  v c  ZW  W',
                   'WSPSv  c  v cZWWWSEW',
                   'WWWWWWbWhWWWW  WWWWW',
                   'Whhb           bhhhW',
                   'W                  W',
                   'WSSSSS SWSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW']
    },

    "world2": {
        'level0': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'W WWW   C C   C C  W',
                   'W C C   C C   C C  W',
                   'W C C   WWW   C C  W',
                   'W C C   C C   WWW  W',
                   'W C C   C C   C C  W',
                   'W C C   C C   C C WW',
                   'W C C   C C   C C  W',
                   'W C C   C C   WWW  W',
                   'W CPC   WWW        W',
                   'W WWW              W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level1': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'WZWWW   C C   C C  W',
                   'W C C   C C   C C  W',
                   'W C C  ZWWW   C C  W',
                   'W C C   C C  ZWWW  W',
                   'W C C   C C   C C  W',
                   'W C C   C C   C C WW',
                   'W C C   C C   C C  W',
                   'W C C   C C   WWWz W',
                   'W CPC   WWWz       W',
                   'W WWWz             W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level2': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'WZWWWz  C C   C C  W',
                   'W C C   C C   C C  W',
                   'W C C  ZWWWz  C C  W',
                   'W C C   C C  ZWWWz W',
                   'W C C   C C   C C  W',
                   'W C C   C C   C C WW',
                   'W C C   C C   C C  W',
                   'W C C   C C  ZWWWz W',
                   'W CPC  ZWWWz       W',
                   'WZWWWz             W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level3': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'WZWWWz  C C   C C  W',
                   'W CsC   C C   C C  W',
                   'W C C  ZWWWz  C C  W',
                   'W C C   CsC  ZWWWz W',
                   'W C C   C C   CsC  W',
                   'W C C   C C   C C WW',
                   'W C C   C C   C C sW',
                   'W C C   C C  ZWWWz W',
                   'W CPC  ZWWWz       W',
                   'WZWWWz             W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level4': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'WZWWWz  C C   C C  W',
                   'W CsC   CSC   C C  W',
                   'W C C  ZWWWz  CSC  W',
                   'W C C   CsC  ZWWWz W',
                   'W C C   C C   CsC  W',
                   'W C C   C C   C C WW',
                   'W C C   C C   C C sW',
                   'W C C   CSC  ZWWWz W',
                   'W CPC  ZWWWz       W',
                   'WZWWWz             W',
                   'WSSSSSSSSSSSSSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level5': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'WZWWWz  C C   C C  W',
                   'W CsC   CSC   C C  W',
                   'W C C  ZWWWz  CSC  W',
                   'W C C   CsC  ZWWWz W',
                   'W C CWb C C   CsC  W',
                   'W C C v C C   C C WW',
                   'W C C v C CZWzC C sW',
                   'W C C WzCSC vZWWWz W',
                   'W CPC vZWWWzv      W',
                   'WZWWWzv     v      W',
                   'WSSSSSvSSSSSvSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level6': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC W C C   C C  W',
                   'WZWWWzv C C   C C  W',
                   'W CsC v CSC   C C  W',
                   'W     vZWWWz  CSC  W',
                   'W C CSv CsC   WWWz W',
                   'W C CWb C C   CsC  W',
                   'W C C v C C S C C WW',
                   'W C C v C C WzC C sW',
                   'W C C WzCSC vZWWWz W',
                   'W CPC vZWWWzv      W',
                   'WZWWWzv     v      W',
                   'WSSSSSvSSSSSvSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level7': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'W WWW   C C   C C  W',
                   'W CsC   CSC   C C  W',
                   'W C C   WWW   CSC  W',
                   'W C C   C C   WWW  W',
                   'W C C   C C   C C  W',
                   'W C C   C C S C C WW',
                   'W C C S C C W C C  W',
                   'W C C W C C v WWW  W',
                   'W CPC v WWW v      W',
                   'WZWWWzv     v      W',
                   'WSSSSSvSSSSSvSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level8': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC   C C   C C  W',
                   'W WWW   C C   C C  W',
                   'W CsC   CSC   C C  W',
                   'W C C   WWW   CSC  W',
                   'W C C   C C   WWW  W',
                   'W C C   C C   C C  W',
                   'W C C   C C S C C WW',
                   'W C C S C C WzC C  W',
                   'W C C WzC CZW WWW  W',
                   'W CPCZW WWW v      W',
                   'WZWWWzv     v      W',
                   'WSSSSSvSSSSSvSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level9': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C C   C C   C C  W',
                   'W CEC S C C   C C  W',
                   'W WWWbW C C S C C  W',
                   'W CsC   CSC W C C  W',
                   'W C C   WWWbW CSC  W',
                   'W C C   C C bhWWW  W',
                   'W C C   C C   C C  W',
                   'W C C   C C S C C WW',
                   'W C C S C C WzC C  W',
                   'W C C WzC CZW WWW  W',
                   'W CPCZW WWW v      W',
                   'WZWWWzv     v      W',
                   'WSSSSSvSSSSSvSSSSSSW',
                   'WWWWWWWWWWWWWWWWWWWW']

    },

    "world3": {
        'level0': ['WWWWWWWWWWWWWWWWWWWW',
                   'W                  W',
                   'W                E W',
                   'W                W W',
                   'W                v W',
                   'W             W  b W',
                   'W             v  v W',
                   'W          W  b  b W',
                   'W          v  v  v W',
                   'W       W  b  b  b W',
                   'W       v  v  v  v W',
                   'W    W  b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level1': ['WWWWWWWWWWWWWWWWWWWW',
                   'W                  W',
                   'W                E W',
                   'W               ZW W',
                   'W                v W',
                   'W            ZW  b W',
                   'W             v  v W',
                   'W         ZW  b  b W',
                   'W          v  v  v W',
                   'W      ZW  b  b  b W',
                   'W       v  v  v  v W',
                   'W   ZW  b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level2': ['WWWWWWWWWWWWWWWWWWWW',
                   'W                  W',
                   'W                E W',
                   'W               ZWzW',
                   'W                v W',
                   'W            ZWz b W',
                   'W             v  v W',
                   'W         ZWz b  b W',
                   'W          v  v  v W',
                   'W      ZWz b  b  b W',
                   'W       v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level3': ['WWWWWWWWWWWWWWWWWWWW',
                   'W    C  C  C ZW    W',
                   'W    C  C  C     E W',
                   'W    C  C ZW    ZWzW',
                   'W    C  C        v W',
                   'W    C ZW    ZWz b W',
                   'W    C        v  v W',
                   'W   ZW    ZWz b  b W',
                   'W          v  v  v W',
                   'W      ZWz b  b  b W',
                   'W       v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level4': ['WWWWWWWWWWWWWWWWWWWW',
                   'W    C  C  C ZW    W',
                   'W    C  C  C     E W',
                   'W    C  C ZWz   ZWzW',
                   'W    C  C        v W',
                   'W    C ZW    ZWz b W',
                   'W    C        v  v W',
                   'W   ZWz   ZWz b  b W',
                   'W          v  v  v W',
                   'W      ZWz b  b  b W',
                   'W       v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level5': ['WWWWWWWWWWWWWWWWWWWW',
                   'W    C  C  C       W',
                   'W    C  C  C     E W',
                   'W    C  C ZWz   ZWzW',
                   'W    C  C        v W',
                   'W    C ZWz   ZWz b W',
                   'W    C     S  v  v W',
                   'W   ZWz   ZWz b  b W',
                   'W       S  v  v  v W',
                   'W      ZWz b  b  b W',
                   'WW   S  v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level6': ['WWWWWWWWWWWWWWWWWWWW',
                   'WsCssCssCssCsss    W',
                   'W C  C  C ZWz    E W',
                   'W C  C  C  s    ZWzW',
                   'W C  C ZWz       v W',
                   'W C  C  s    ZWz b W',
                   'W C ZWz       v  v W',
                   'W C  s    ZWz b  b W',
                   'W Wz       v  v  v W',
                   'W s    ZWz b  b  b W',
                   'W       v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level7': ['WWWWWWWWWWWWWWWWWWWW',
                   'WsCssCs C  C  s    W',
                   'W C  C  C  W     E W',
                   'W C  C  C  s    ZWzW',
                   'W C  C  W        v W',
                   'W C  C  s    ZWz b W',
                   'W C  Wz    S  v  v W',
                   'W C  s    ZWz b  b W',
                   'W W     S  v  v  v W',
                   'W s    ZWz b  b  b W',
                   'W   ZWz v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level8': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C  C  C  C  C    W',
                   'W C  C  C  WWWW  E W',
                   'W C  C  C  s    ZWzW',
                   'W C  C  W     S  v W',
                   'W C  C  s    ZWz b W',
                   'W C  Wz    S  v  v W',
                   'W C  s    ZWz b  b W',
                   'W Wz    S  v  v  v W',
                   'W s    ZWz b  b  b W',
                   'W   ZWz v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW'],
        'level9': ['WWWWWWWWWWWWWWWWWWWW',
                   'W C  C  C  C  C    W',
                   'W C  C  C  WWWW  E W',
                   'W C  C  C  s    ZWzW',
                   'W C  C  W     S  v W',
                   'W C  C  s    ZWz b W',
                   'W C ZWz       v  v W',
                   'W C  s    ZWz b  b W',
                   'WZWz    S  v  v  v W',
                   'W s    ZWz b  b  b W',
                   'W   ZWz v  v  v  v W',
                   'W   ZWz b  b  b  b W',
                   'W P  v  v  v  v  v W',
                   'WSWSSbSSbSSbSSbSSbSW',
                   'WWWWWWWWWWWWWWWWWWWW']
    }
}

level_order = [levels["world0"]["title"]]


for i in range(30):
    level_order.append(levels["world" + str(i // 10 + 1)]["level" + str(i % 10)])

level_order.append(levels["world0"]["ending"])
